# docker-compose.yml
version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "9090:80"
    container_name: backend

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    container_name: frontend
