name: CI For Backend

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main
  pull_request:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  php-and-docker:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Set up PHP for linting
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    # 3️⃣ Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 4️⃣ Build Docker image (tag with SHA + latest)
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }} -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest .

    # 5️⃣ Push Docker image (both tags)
    - name: Push Docker image (SHA tag)
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}
      
    - name: Push Docker image (latest tag)
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest